function [] = prettyfy(TitleName, x, y)
if nargin == 0
    TitleName = 'Missing Title'; x = ''; y = '';
elseif nargin == 1
    x = ''; y = '';
end

PAPER = get( gcf , 'Position' );
set ( gcf , 'PaperSize' , [PAPER(3) PAPER(4)] );
set( gca , ...
'FontSize' , 30 ,...
'FontName' , 'Helvetica' )
title(TitleName)
xlabel(x)
ylabel(y)
set(gca,'LineWidth',2,'TickLength',[0.025 0.025]);
set(gca,'XMinorTick','on','YMinorTick','on')
set(gcf , 'PaperUnits' , 'Centimeters' ,...
'Units' , 'Centimeters' ,...
'PaperOrientation' , 'Portrait' ,...
'PaperPositionMode' , 'auto' ,...
'Position' , [1 1 40 20] );
set(gcf, 'units','normalized','outerposition',[0 0 1 1])
set( gca , 'Units' , 'centimeters' ,...
'Position' , [3 3 28 14] ,...
'FontSize' , 25 ,...
'FontName' , 'Helvetica' )
end